import Head from 'next/head'
import { DndProvider } from 'react-dnd'
import { HTML5Backend } from 'react-dnd-html5-backend'
import Header from '../components/Header'
import ToDoList from '../components/ToDoList'
import Carousel from '../components/Carousel'
import Forms from '../components/Forms'
import Footer from '../components/Footer'

function Home() {
  return (
    <div>
      <DndProvider backend={HTML5Backend}>
        <Head>
          <title>Coopers</title>
          <meta name='description' content='Generated by create next app' />
          <link href='fonts/fonts.css' rel='stylesheet' />
          <link href='https://fonts.cdnfonts.com/css/soleil' rel='stylesheet' />
          <link
            href='https://fonts.googleapis.com/css?family=Montserrat'
            rel='stylesheet'
          />
          <link
            href='https://fonts.googleapis.com/css?family=Poppins'
            rel='stylesheet'
          />
          <link
            href='https://fonts.googleapis.com/css2?family=Inter&display=optional'
            rel='stylesheet'
          />
        </Head>
        <Header />
        <ToDoList />
        <Carousel />
        <Forms />
        <Footer />
      </DndProvider>
    </div>
  )
}

export default Home
