import Head from 'next/head'
import Header from '../components/Header'
import ToDoList from '../components/ToDoList'
import Carousel from '../components/Carousel'
import Forms from '../components/Forms'
import Footer from '../components/Footer'

function Home(props) {
  const header_images = props.images
  const header_text = props.text
  const to_do_images = props.images
  const to_do_texts = props.text
  const carousel_img = props.carousel_images
  const forms_images = props.images
  const footer_images = props.images
  const footer_text = props.text
  return (
    <div>
      <Head>
        <title>Coopers</title>
        <meta name='description' content='Generated by create next app' />
        <link href='fonts/fonts.css' rel='stylesheet' />
        <link href='https://fonts.cdnfonts.com/css/soleil' rel='stylesheet' />
        <link
          href='https://fonts.googleapis.com/css?family=Montserrat'
          rel='stylesheet'
        />
        <link
          href='https://fonts.googleapis.com/css?family=Poppins'
          rel='stylesheet'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Inter&display=optional'
          rel='stylesheet'
        />
      </Head>
      <Header headerImages={header_images} headerText={header_text} />
      <ToDoList ToDoImages={to_do_images} ToDoText={to_do_texts} />
      <Carousel CarouselImages={carousel_img} />
      <Forms FormsImages={forms_images} />
      <Footer FooterImages={footer_images} FooterText={footer_text} />
    </div>
  )
}

export async function getStaticProps({ res }) {
  const get_images = await fetch(
    'https://dario.marbr.net/wp-json/wp/v2/pages/406',
    {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    }
  )

  const get_text = await fetch(
    'https://dario.marbr.net/wp-json/wp/v2/pages/51',
    {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    }
  )

  const get_carousel_images_api = await fetch(
    'https://dario.marbr.net/wp-json/wp/v2/pages/84',
    {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    }
  )

  const result_text = await get_text.json()
  const result_image = await get_images.json()
  const result_carousel_image = await get_carousel_images_api.json()

  return {
    props: {
      images: result_image.acf,
      text: result_text.acf,
      carousel_images: result_carousel_image.acf,
    },
  }
}

export default Home
