import Head from 'next/head'
import { DndProvider } from 'react-dnd'
import { HTML5Backend } from 'react-dnd-html5-backend'
import Header  from '../components/Header'
import ToDoList   from '../components/ToDoList'
import Carousel from '../components/Carousel'
import Forms from '../components/Forms'
import Footer from '../components/Footer'
import Drag from '../components/Drag'

function Home() {
  return (
    <div >
    <DndProvider backend={HTML5Backend}>
      <Head>
        <title>Coopers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ToDoList />
      <Carousel />
      <Forms />
      <Footer />
      <Drag />
    </DndProvider>
    </div>
  )
}

export default Home
